#!/usr/bin/env node
/**
 * Download nqui skills to a consumer project.
 *
 * Usage: npx @nlib/nqui init-skills
 *
 * SSOT: packages/nqui/docs/nqui-skills/
 *   - All nqui skills (nqui-components, nqui-design-system, nqui-shadcn, etc.)
 *   - Impeccable design skills (audit, polish, layout, etc.)
 *
 * Copies docs/nqui-skills/ → .cursor/nqui-skills/
 * Copies docs/components/   → .cursor/nqui-skills/components/  (per-component docs)
 * Creates AGENTS.md pointing to .cursor/nqui-skills/SKILL.md
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, cpSync } from 'fs';
import { join, resolve } from 'path';
import { getPackageRoot } from './getPackageRoot.js';
import { resolveTargetDir } from './resolve-target-dir.js';

const root = getPackageRoot();
const SKILLS_SOURCE = join(root, 'docs', 'nqui-skills');
const COMPONENTS_SOURCE = join(root, 'docs', 'components');

function ensureDir(dir) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

export async function downloadSkills({ force = true }) {
  const targetDir = resolveTargetDir(process.cwd());
  const cursorDir = join(targetDir, '.cursor');
  const skillsDest = join(cursorDir, 'nqui-skills');
  const componentsDest = join(skillsDest, 'components');
  const agentsFile = join(targetDir, 'AGENTS.md');

  ensureDir(cursorDir);

  // Copy nqui-skills/ → .cursor/nqui-skills/
  if (existsSync(SKILLS_SOURCE)) {
    if (existsSync(skillsDest) && !force) {
      console.log('⏭️  nqui-skills already exists. Use --force to overwrite.');
    } else {
      if (existsSync(skillsDest)) {
        cpSync(skillsDest, skillsDest + '.backup', { recursive: true });
      }
      cpSync(SKILLS_SOURCE, skillsDest, { recursive: true, force });
      console.log('✅ Copied .agents/skills/ →', skillsDest);
    }
  } else {
    console.warn('⚠️  Source skills not found:', SKILLS_SOURCE);
    return;
  }

  // Copy per-component docs: docs/components/ → .cursor/nqui-skills/components/
  if (existsSync(COMPONENTS_SOURCE)) {
    if (existsSync(componentsDest) && !force) {
      console.log('⏭️  nqui-skills/components already exists. Use --force to overwrite.');
    } else {
      cpSync(COMPONENTS_SOURCE, componentsDest, { recursive: true, force });
      console.log('✅ Copied component docs to:', componentsDest);
    }
  } else {
    console.warn('⚠️  Source component docs not found:', COMPONENTS_SOURCE);
  }

  // Create or update AGENTS.md
  const agentsContent = `# AGENTS.md

This file points to nqui skills for AI assistants.

## nqui Skills (SSOT: packages/nqui/docs/nqui-skills/)

All skills are stored in the nqui package at:

\`\`\`
.cursor/nqui-skills/SKILL.md   ← hub / index
\`\`\`

Skills available under \`.cursor/nqui-skills/\`:

| Skill | Purpose |
|-------|---------|
| **nqui-components** | Component selection, props, examples |
| **nqui-design-system** | Design tokens, spacing, Card + ScrollArea |
| **nqui-shadcn** | shadcn composition, forms, icons |
| **nqui-install** | Setup, install peers, CSS init |
| **nqui-bundle-size-best-practices** | Bundle size when adding deps |
| **nqui-local-published-toggle** | Switch local ↔ published nqui |
| **impeccable** | Design quality, AI-slop avoidance |
| **/audit**, **/polish**, **/layout**, etc. | Impeccable design commands |

## How to Use

When working with nqui components, AI assistants should:

1. Load \`.cursor/nqui-skills/SKILL.md\` — the hub index
2. Open sub-skills by task (e.g. \`nqui-components/SKILL.md\`)
3. For component docs: \`.cursor/nqui-skills/COMPONENTS_INDEX.md\` → one \`components/nqui-<name>.md\`

## Impeccable Design Skills

Run \`/impeccable teach\` first to establish design context, then use commands like:

- \`/audit input-group\` — audit a specific component
- \`/polish\` — cleanup UI inconsistencies
- \`/layout\` — fix spacing / alignment

---

Generated by nqui. Run \`npx @nqlib/nqui init-skills --force\` to update.
`;

  if (existsSync(agentsFile) && !force) {
    console.log('⏭️  AGENTS.md already exists. Use --force to overwrite.');
  } else {
    writeFileSync(agentsFile, agentsContent);
    console.log('✅ Created AGENTS.md at:', agentsFile);
  }

  console.log('\n📚 nqui-skills installed!');
  console.log('   Restart Cursor to load the skills.');
}

// CLI execution
const args = process.argv.slice(2);
const force = args.includes('--force') || args.length === 0;

downloadSkills({ force }).catch(console.error);
